version: 2

builds:
  - main: ./cmd/postfix_exporter
    ldflags: |
      -s
      -X github.com/prometheus/common/version.Version={{.Version}}
      -X github.com/prometheus/common/version.Revision={{.FullCommit}}
      -X github.com/prometheus/common/version.Branch={{.Branch}}
      -X github.com/prometheus/common/version.BuildUser={{.Env.USER}}@{{.Env.HOSTNAME}}
      -X github.com/prometheus/common/version.BuildDate={{time "20060102-15:04:05"}}
    tags:
      - netgo
    targets:
      # - aix_ppc64
      - darwin_amd64
      - darwin_arm64
      - dragonfly_amd64
      - freebsd_386
      - freebsd_amd64
      - freebsd_arm64
      - freebsd_arm_6
      - freebsd_arm_7
      - illumos_amd64
      - linux_386
      - linux_amd64
      - linux_arm64
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_mips
      - linux_mips64
      - linux_mips64le
      - linux_mipsle
      - linux_ppc64
      - linux_ppc64le
      - linux_riscv64
      - linux_s390x
      - netbsd_386
      - netbsd_amd64
      - netbsd_arm64
      - netbsd_arm_6
      - netbsd_arm_7
      - openbsd_386
      - openbsd_amd64
      - openbsd_arm64
      - openbsd_arm_7
      - windows_386
      - windows_amd64
      - windows_arm64
    overrides:
      - goos: linux
        goarch: '386'
        go386: sse2
        env:
          - CGO_ENABLED=1
          - CC=i686-linux-gnu-gcc
      - goos: linux
        goarch: amd64
        goamd64: v1
        env:
          - CGO_ENABLED=1
          - CC=x86_64-linux-gnu-gcc
      - goos: linux
        goarch: arm64
        goarm64: v8.0
        env:
          - CGO_ENABLED=1
          - CC=aarch64-linux-gnu-gcc
      - goos: linux
        goarch: arm
        goarm: '5'
        env:
          - CGO_ENABLED=1
          - CC=arm-linux-gnueabi-gcc
      - goos: linux
        goarch: arm
        goarm: '6'
        env:
          - CGO_ENABLED=1
          - CC=arm-linux-gnueabi-gcc
      - goos: linux
        goarch: arm
        goarm: '7'
        env:
          - CGO_ENABLED=1
          - CC=arm-linux-gnueabi-gcc
      - goos: linux
        goarch: mips
        gomips: hardfloat
        env:
          - CGO_ENABLED=1
          - CC=mips-linux-gnu-gcc
      - goos: linux
        goarch: mips64
        gomips: hardfloat
        env:
          - CGO_ENABLED=1
          - CC=mips64-linux-gnuabi64-gcc
      - goos: linux
        goarch: mips64le
        gomips: hardfloat
        env:
          - CGO_ENABLED=1
          - CC=mips64el-linux-gnuabi64-gcc
      - goos: linux
        goarch: mipsle
        gomips: hardfloat
        env:
          - CGO_ENABLED=1
          - CC=mipsel-linux-gnu-gcc
      - goos: linux
        goarch: ppc64le
        goppc64: power8
        env:
          - CGO_ENABLED=1
          - CC=powerpc64le-linux-gnu-gcc
      - goos: linux
        goarch: riscv64
        goriscv64: rva20u64
        env:
          - CGO_ENABLED=1
          - CC=riscv64-linux-gnu-gcc
      - goos: linux
        goarch: s390x
        env:
          - CGO_ENABLED=1
          - CC=s390x-linux-gnu-gcc

archives:
  - format_overrides:
      - goos: windows
        format: zip

release:
  prerelease: auto
