on:
  schedule:
    - cron: '0 6 * * 0'
      timezone: 'Europe/Moscow'
  workflow_dispatch:
permissions:
  contents: write
  packages: write
name: Auto Release
jobs:
  auto_release:
    name: Auto Release
    uses: sergeymakinen/.github/.github/workflows/auto-release.yml@main
    secrets: inherit
  release:
    name: Release
    needs: auto_release
    if: needs.auto_release.outputs.next-tag != ''
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ needs.auto_release.outputs.next-tag }}
    secrets: inherit
