on:
  push:
    tags:
      - '*'
name: goreleaser
jobs:
  GoReleaser:
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - name: Install git
        run: |
          apt-get update
          apt-get install -y git
      - name: 'Workaround: mark every directory as safe for Git'
        run: git config --global --add safe.directory '*'
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.x
          check-latest: true
      - name: Install cgo dependencies
        run: |
          apt-get install -y \
            build-essential \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi \
            gcc-i686-linux-gnu \
            gcc-mips-linux-gnu \
            gcc-mips64-linux-gnuabi64 \
            gcc-mips64el-linux-gnuabi64 \
            gcc-mipsel-linux-gnu \
            gcc-powerpc64le-linux-gnu \
            gcc-riscv64-linux-gnu \
            gcc-s390x-linux-gnu \
            gcc-x86-64-linux-gnu \
            libsystemd-dev
      - name: Set build info
        run: |
          echo "USER=$(whoami)" >> $GITHUB_ENV
          echo "HOSTNAME=$(hostname)" >> $GITHUB_ENV
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER: ${{ env.USER }}
          HOSTNAME: ${{ env.HOSTNAME }}
