on:
  push:
    tags:
      - '*'
name: goreleaser
jobs:
  GoReleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install cgo dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsystemd-dev
      - name: Set build info
        run: |
          echo "USER=$(whoami)" >> $GITHUB_ENV
          echo "HOSTNAME=$(hostname)" >> $GITHUB_ENV
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER: ${{ env.USER }}
          HOSTNAME: ${{ env.HOSTNAME }}
