on:
  push:
    tags:
      - '*'
name: goreleaser
jobs:
  GoReleaser:
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
      - name: Install git
        run: |
          apt-get update
          apt-get install -y git
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install cgo dependencies
        run: apt-get install -y build-essential libsystemd-dev
      - name: Set build info
        run: |
          echo "USER=$(whoami)" >> $GITHUB_ENV
          echo "HOSTNAME=$(hostname)" >> $GITHUB_ENV
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER: ${{ env.USER }}
          HOSTNAME: ${{ env.HOSTNAME }}
