on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 1 * *'
name: tests
jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.14.x
          - 1.15.x
          - 1.16.x
          - 1.17.x
          - 1.18.x
          - 1.19.x
          - 1.x
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install cgo dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsystemd-dev
      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
