on:
  push:
    branches:
      - '**'
  pull_request:
name: Test
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: Install cgo dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libsystemd-dev
      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
